grails-app/controllers/com/luckydog/common/AddressController.groovy
package com.luckydog.common



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AddressController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Address.list(params), model:[addressInstanceCount: Address.count()]
    }

    def show(Address addressInstance) {
        respond addressInstance
    }

    def create() {
        respond new Address(params)
    }

    @Transactional
    def save(Address addressInstance) {
        if (addressInstance == null) {
            notFound()
            return
        }

        if (addressInstance.hasErrors()) {
            respond addressInstance.errors, view:'create'
            return
        }

        addressInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'address.label', default: 'Address'), addressInstance.id])
                redirect addressInstance
            }
            '*' { respond addressInstance, [status: CREATED] }
        }
    }

    def edit(Address addressInstance) {
        respond addressInstance
    }

    @Transactional
    def update(Address addressInstance) {
        if (addressInstance == null) {
            notFound()
            return
        }

        if (addressInstance.hasErrors()) {
            respond addressInstance.errors, view:'edit'
            return
        }

        addressInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Address.label', default: 'Address'), addressInstance.id])
                redirect addressInstance
            }
            '*'{ respond addressInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Address addressInstance) {

        if (addressInstance == null) {
            notFound()
            return
        }

        addressInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Address.label', default: 'Address'), addressInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'address.label', default: 'Address'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/address/_form.gsp
<%@ page import="com.luckydog.common.Address" %>



<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'addressOne', 'error')} ">
	<label for="addressOne">
		<g:message code="address.addressOne.label" default="Address One" />
		
	</label>
	<g:textField name="addressOne" value="${addressInstance?.addressOne}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'addressTwo', 'error')} ">
	<label for="addressTwo">
		<g:message code="address.addressTwo.label" default="Address Two" />
		
	</label>
	<g:textField name="addressTwo" value="${addressInstance?.addressTwo}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'city', 'error')} ">
	<label for="city">
		<g:message code="address.city.label" default="City" />
		
	</label>
	<g:select id="city" name="city.id" from="${com.luckydog.location.CityLocation.list(max:100)}" optionKey="id" required="" value="${addressInstance?.city?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="address.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${addressInstance?.description}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'email', 'error')} ">
	<label for="email">
		<g:message code="address.email.label" default="Email" />
		
	</label>
	<g:textField name="email" value="${addressInstance?.email}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'fax', 'error')} ">
	<label for="fax">
		<g:message code="address.fax.label" default="Fax" />
		
	</label>
	<g:textField name="fax" value="${addressInstance?.fax}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'isPrimary', 'error')} ">
	<label for="isPrimary">
		<g:message code="address.isPrimary.label" default="Is Primary" />
		
	</label>
	<g:checkBox name="isPrimary" value="${addressInstance?.isPrimary}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'phone', 'error')} ">
	<label for="phone">
		<g:message code="address.phone.label" default="Phone" />
		
	</label>
	<g:select name="phone" from="${com.luckydog.common.Phone.list()}" multiple="multiple" optionKey="id" size="5" required="" value="${addressInstance?.phone*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'postCode', 'error')} ">
	<label for="postCode">
		<g:message code="address.postCode.label" default="Post Code" />
		
	</label>
	<g:textField name="postCode" value="${addressInstance?.postCode}" />

</div>

<div class="fieldcontain ${hasErrors(bean: addressInstance, field: 'website', 'error')} ">
	<label for="website">
		<g:message code="address.website.label" default="Website" />
		
	</label>
	<g:textField name="website" value="${addressInstance?.website}" />

</div>

grails-app/views/address/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="homepage" />
		<g:set var="entityName" value="${message(code: 'address.label', default: 'Address')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
	<div class="container">
			<div class="nav" role="navigation">
			<ul>
				
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-address" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${addressInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${addressInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:addressInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
		</div>
	</body>
</html>

grails-app/views/address/edit.gsp
<%@ page import="com.luckydog.common.Address" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="homepage" />
		<g:set var="entityName" value="${message(code: 'address.label', default: 'Address')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
	<div class="container">
			<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-address" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${addressInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${addressInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:addressInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${addressInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
		</div>
	</body>
</html>

grails-app/views/address/index.gsp
<%@ page import="com.luckydog.common.Address" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="homepage" />
		<g:set var="entityName" value="${message(code: 'address.label', default: 'Address')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
	<div class="container">
		
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		
		<div id="list-address" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table width="100%">
			<thead>
					<tr>
					
						<g:sortableColumn property="addressOne" title="${message(code: 'address.addressOne.label', default: 'Address One')}" />
					
						<g:sortableColumn property="addressTwo" title="${message(code: 'address.addressTwo.label', default: 'Address Two')}" />
					
						<th><g:message code="address.city.label" default="City" /></th>
					
						<g:sortableColumn property="description" title="${message(code: 'address.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'address.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="fax" title="${message(code: 'address.fax.label', default: 'Fax')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${addressInstanceList}" status="i" var="addressInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${addressInstance.id}">${fieldValue(bean: addressInstance, field: "addressOne")}</g:link></td>
					
						<td>${fieldValue(bean: addressInstance, field: "addressTwo")}</td>
					
						<td>${fieldValue(bean: addressInstance, field: "city")}</td>
					
						<td>${fieldValue(bean: addressInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: addressInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: addressInstance, field: "fax")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${addressInstanceCount ?: 0}" />
			</div>
		</div>
		
		</div>
	</body>
</html>

grails-app/views/address/show.gsp
<%@ page import="com.luckydog.common.Address" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="homepage" />
		<g:set var="entityName" value="${message(code: 'address.label', default: 'Address')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
	
		<div class="container">
		
		<div class="nav" role="navigation">
			<ul>
				
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-address" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list address">
			
				<g:if test="${addressInstance?.addressOne}">
				<blockquote>
				<li class="fieldcontain">
					<span id="addressOne-label" class="property-label"><g:message code="address.addressOne.label" default="Address One" /></span>
					
						<span class="property-value" aria-labelledby="addressOne-label"><g:fieldValue bean="${addressInstance}" field="addressOne"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.addressTwo}">
				<blockquote>
				<li class="fieldcontain">
					<span id="addressTwo-label" class="property-label"><g:message code="address.addressTwo.label" default="Address Two" /></span>
					
						<span class="property-value" aria-labelledby="addressTwo-label"><g:fieldValue bean="${addressInstance}" field="addressTwo"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.city}">
				<blockquote>
				<li class="fieldcontain">
					<span id="city-label" class="property-label"><g:message code="address.city.label" default="City" /></span>
					
						<span class="property-value" aria-labelledby="city-label"><g:link controller="cityLocation" action="show" id="${addressInstance?.city?.id}">${addressInstance?.city?.encodeAsHTML()}</g:link></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.description}">
				<blockquote>
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="address.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${addressInstance}" field="description"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.email}">
				<blockquote>
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="address.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${addressInstance}" field="email"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.fax}">
				<blockquote>
				<li class="fieldcontain">
					<span id="fax-label" class="property-label"><g:message code="address.fax.label" default="Fax" /></span>
					
						<span class="property-value" aria-labelledby="fax-label"><g:fieldValue bean="${addressInstance}" field="fax"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.isPrimary}">
				<blockquote>
				<li class="fieldcontain">
					<span id="isPrimary-label" class="property-label"><g:message code="address.isPrimary.label" default="Is Primary" /></span>
					
						<span class="property-value" aria-labelledby="isPrimary-label"><g:formatBoolean boolean="${addressInstance?.isPrimary}" /></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.phone}">
				<blockquote>
				<li class="fieldcontain">
					<span id="phone-label" class="property-label"><g:message code="address.phone.label" default="Phone" /></span>
					
						<g:each in="${addressInstance.phone}" var="p">
						<span class="property-value" aria-labelledby="phone-label"><g:link controller="phone" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.postCode}">
				<blockquote>
				<li class="fieldcontain">
					<span id="postCode-label" class="property-label"><g:message code="address.postCode.label" default="Post Code" /></span>
					
						<span class="property-value" aria-labelledby="postCode-label"><g:fieldValue bean="${addressInstance}" field="postCode"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
				<g:if test="${addressInstance?.website}">
				<blockquote>
				<li class="fieldcontain">
					<span id="website-label" class="property-label"><g:message code="address.website.label" default="Website" /></span>
					
						<span class="property-value" aria-labelledby="website-label"><g:fieldValue bean="${addressInstance}" field="website"/></span>
					
				</li>
				</blockquote>
				</g:if>
			
			</ol>
			<g:form url="[resource:addressInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${addressInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
		</div>
	</body>
</html>